### ISSUE TITLE
Please update to support latest stylelint@10.x

### ISSUE THREAD

**Issue by JustFly1984** [juanca/stylelint-css-modules#5]

**Comment by juanca** [comment]
I just ran this plugin with stylelint@10.1.0 and it works! Pushing changes in a second.

**Comment by juanca** [comment]
Please update to ^0.9.0

Let me know if you encounter any other errors or concerns

**Comment by juanca** [comment]
See latest release @ https://github.com/juanca/stylelint-css-modules/releases/tag/1.1.0
