### ISSUE TITLE
Please update to support stylelint@11

### ISSUE THREAD

**Issue by JustFly1984** [juanca/stylelint-css-modules#9]
currently I see warnings in my yarn install logs then I try to update stylelint@11, that stylelint-css-modules@0.9.0 requires stylelint@10

all other plugins I have already support stylelint@11 

Thank you for your project!

**Comment by JustFly1984** [comment]
created PR #12 please review and publish

**Comment by juanca** [comment]
I don't know how I didn't see notification. I just re-watched the repo. I'll see if I can get this stuff up-to-date by EOW.

**Comment by juanca** [comment]
See latest release @ https://github.com/juanca/stylelint-css-modules/releases/tag/1.1.0
